spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/payflow_merchant

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
